### ISSUE TITLE
improvents

### ISSUE THREAD

**Issue by prestarocket** [Adel010/Facebook-Pixel-Prestashop-Free-Module#1]
maybe use getTemplateVars() to get $product and $breadcrumb (for categories) and so save on db requests

https://github.com/Adel010/Facebook-Pixel-Prestashop-Free-Module/blob/master/facebookpixelinstaller.php#L270-L272

wdyt ?

**Comment by Adel010** [comment]
I just fixed it, thank you for having suggest that I appreciate it
